# Irma Wahyu Rosanti (06211640000002)
### Restaurant & Consumer Data
##### Sumber : UCI Machine Learning Repository

In [29]:
import pandas as pd
import numpy as np

### Load Data

In [30]:
Biodata = pd.read_csv (r'e:\Documents\userprofile.csv', delimiter=';') 
Lokasi = pd.read_csv(r'e:\Documents\places.csv', delimiter=';')
Rating = pd.read_csv(r'e:\Documents\rating_final.csv', delimiter=';')
Pembayaran = pd.read_csv(r'e:\Documents\userpayment.csv', delimiter=';')

In [31]:
Biodata

,userID,transport,marital_status,birth_year,religion,activity,weight,budget,height
0,U1001,on foot,single,1989,none,student,69,medium,1.77
1,U1002,public,single,1990,Catholic,student,40,low,1.87
2,U1003,public,single,1989,Catholic,student,60,low,1.69
3,U1004,public,single,1940,none,professional,44,medium,1.53
4,U1005,public,single,1992,Catholic,student,65,medium,1.69
5,U1006,car owner,single,1989,none,student,75,medium,1.80
6,U1007,public,single,1989,Catholic,student,60,low,1.59
7,U1008,public,single,1989,Catholic,student,68,low,1.72
8,U1009,on foot,single,1991,Catholic,student,75,medium,1.78
9,U1010,car owner,married,1987,none,student,40,medium,1.67
10,U1011,public,single,1989,Catholic,student,68,medium,1.78
11,U1012,public,single,1988,Catholic,student,98,medium,1.84
12,U1013,public,widow,1982,none,professional,80,medium,1.75
13,U1014,public,single,1990,Catholic,student,53,medium,1.69
14,U1015,public,single,1989,Catholic,student,87,medium,1.67
15,U1016,on foot,single,1991,Catholic,student,70,medium,1.67
16,U1017,public,single,1991,none,professional,79,medium,1.79
17,U1018,public,single,1989,Christian,student,65,low,1.83
18,U1019,public,single,1989,Catholic,student,59,medium,1.60
19,U1020,public,single,1982,Catholic,professional,40,medium,1.68
20,U1021,car owner,single,1984,Catholic,student,108,medium,1.62
21,U1022,car owner,single,1990,Catholic,student,46,medium,1.54
22,U1023,car owner,single,1988,Catholic,student,103,low,1.79
23,U1024,?,?,1930,none,?,40,?,1.20
24,U1025,public,single,1990,Catholic,student,65,medium,1.79
25,U1026,public,single,1989,Catholic,student,49,medium,1.55
26,U1027,public,single,1989,Catholic,student,60,low,1.65
27,U1028,public,single,1989,Christian,student,77,medium,1.63
28,U1029,public,single,1990,Catholic,student,58,low,1.60
29,U1030,on foot,single,1991,Catholic,student,64,medium,1.75
...,...,...,...,...,...,...,...,...,...
108,U1109,public,single,1989,Catholic,student,57,low,1.72
109,U1110,car owner,single,1993,Catholic,student,85,medium,1.75
110,U1111,car owner,single,1991,Catholic,student,69,medium,1.69
111,U1112,car owner,single,1991,Catholic,student,69,medium,1.69
112,U1113,public,single,1990,Catholic,student,75,medium,1.73
113,U1114,on foot,single,1991,Catholic,student,58,medium,1.68
114,U1115,public,single,1990,Catholic,student,76,low,1.76
115,U1116,public,married,1987,Catholic,student,40,medium,1.71
116,U1117,public,single,1982,Catholic,professional,58,medium,1.60
117,U1118,public,single,1987,none,student,60,medium,1.68
118,U1119,public,single,1992,Catholic,student,68,medium,1.68
119,U1120,public,single,1930,none,student,47,low,1.57
120,U1121,public,married,1987,Catholic,working-class,90,medium,1.60
121,U1122,?,?,1930,none,?,40,?,1.20
122,U1123,?,single,1987,Catholic,student,110,medium,1.75
123,U1124,public,single,1991,Catholic,student,51,low,1.20
124,U1125,public,single,1990,Catholic,student,57,low,1.67
125,U1126,on foot,single,1990,Catholic,student,65,low,1.63
126,U1127,public,single,1992,Catholic,student,65,low,1.76
127,U1128,public,single,1986,Catholic,student,66,low,1.72
128,U1129,public,single,1989,none,student,69,low,1.69
129,U1130,?,?,1989,none,?,40,?,1.20
130,U1131,car owner,married,1990,none,student,90,medium,1.80
131,U1132,public,single,1991,none,student,55,?,1.60
132,U1133,car owner,single,1991,none,student,60,medium,1.57
133,U1134,public,single,1991,Catholic,student,52,medium,1.65
134,U1135,on foot,single,1988,Catholic,student,66,low,1.54
135,U1136,car owner,single,1990,Catholic,student,50,low,1.60
136,U1137,public,single,1989,Catholic,student,72,low,1.78
137,U1138,public,single,1991,none,student,54,medium,1.55

In [32]:
#Menghapus Kolom
Biodata = Biodata.drop(['transport', 'marital_status','weight','height'], axis=1)
Biodata

    userID  birth_year   religion       activity  budget
0    U1001        1989       none        student  medium
1    U1002        1990   Catholic        student     low
2    U1003        1989   Catholic        student     low
3    U1004        1940       none   professional  medium
4    U1005        1992   Catholic        student  medium
5    U1006        1989       none        student  medium
6    U1007        1989   Catholic        student     low
7    U1008        1989   Catholic        student     low
8    U1009        1991   Catholic        student  medium
9    U1010        1987       none        student  medium
10   U1011        1989   Catholic        student  medium
11   U1012        1988   Catholic        student  medium
12   U1013        1982       none   professional  medium
13   U1014        1990   Catholic        student  medium
14   U1015        1989   Catholic        student  medium
15   U1016        1991   Catholic        student  medium
16   U1017        1991       none   professional  medium
17   U1018        1989  Christian        student     low
18   U1019        1989   Catholic        student  medium
19   U1020        1982   Catholic   professional  medium
20   U1021        1984   Catholic        student  medium
21   U1022        1990   Catholic        student  medium
22   U1023        1988   Catholic        student     low
23   U1024        1930       none              ?       ?
24   U1025        1990   Catholic        student  medium
25   U1026        1989   Catholic        student  medium
26   U1027        1989   Catholic        student     low
27   U1028        1989  Christian        student  medium
28   U1029        1990   Catholic        student     low
29   U1030        1991   Catholic        student  medium
..     ...         ...        ...            ...     ...
108  U1109        1989   Catholic        student     low
109  U1110        1993   Catholic        student  medium
110  U1111        1991   Catholic        student  medium
111  U1112        1991   Catholic        student  medium
112  U1113        1990   Catholic        student  medium
113  U1114        1991   Catholic        student  medium
114  U1115        1990   Catholic        student     low
115  U1116        1987   Catholic        student  medium
116  U1117        1982   Catholic   professional  medium
117  U1118        1987       none        student  medium
118  U1119        1992   Catholic        student  medium
119  U1120        1930       none        student     low
120  U1121        1987   Catholic  working-class  medium
121  U1122        1930       none              ?       ?
122  U1123        1987   Catholic        student  medium
123  U1124        1991   Catholic        student     low
124  U1125        1990   Catholic        student     low
125  U1126        1990   Catholic        student     low
126  U1127        1992   Catholic        student     low
127  U1128        1986   Catholic        student     low
128  U1129        1989       none        student     low
129  U1130        1989       none              ?       ?
130  U1131        1990       none        student  medium
131  U1132        1991       none        student       ?
132  U1133        1991       none        student  medium
133  U1134        1991   Catholic        student  medium
134  U1135        1988   Catholic        student     low
135  U1136        1990   Catholic        student     low
136  U1137        1989   Catholic        student     low
137  U1138        1991       none        student  medium

[138 rows x 5 columns]

In [33]:
Lokasi

,placeID,city,state,country,alcohol,smoking_area,price,other_services
0,134999,Cuernavaca,Morelos,Mexico,No_Alcohol_Served,none,medium,none
1,132825,s.l.p.,s.l.p.,mexico,No_Alcohol_Served,none,low,none
2,135106,San Luis Potosi,San Luis Potosi,Mexico,Wine-Beer,only at bar,medium,none
3,132667,victoria,tamaulipas,?,No_Alcohol_Served,none,low,none
4,132613,victoria,Tamaulipas,Mexico,No_Alcohol_Served,permitted,medium,none
5,135040,San Luis Potosi,SLP,Mexico,Wine-Beer,none,high,none
6,132732,Cd Victoria,Tamaulipas,Mexico,No_Alcohol_Served,none,low,none
7,132875,?,?,?,Wine-Beer,section,high,Internet
8,132609,victoria,Tamaulipas,Mexico,No_Alcohol_Served,not permitted,low,none
9,135082,San Luis Potosi,SLP,Mexico,No_Alcohol_Served,none,medium,none
10,135070,San Luis Potosi,SLP,Mexico,No_Alcohol_Served,none,medium,none
11,135069,San Luis Potosi,SLP,Mexico,Wine-Beer,none,low,none
12,135065,San Luis Potosi,SLP,Mexico,Wine-Beer,section,high,none
13,135076,San Luis Potosi,SLP,Mexico,Wine-Beer,none,high,none
14,135086,San Luis Potosi,SLP,Mexico,No_Alcohol_Served,not permitted,medium,none
15,132870,San Luis Potosi,San Luis Potosi,Mexico,No_Alcohol_Served,not permitted,low,none
16,132854,San Luis Potosi,San Luis Potosi,Mexico,Wine-Beer,none,medium,none
17,132937,san luis potosi,san luis potosi,mexico,Full_Bar,section,low,variety
18,132856,San Luis Potosi,San Luis Potosi,Mexico,Wine-Beer,none,low,none
19,132668,victoria,tamaulipas,mexico,No_Alcohol_Served,none,low,none
20,135033,San Luis Potosi,SLP,Mexico,No_Alcohol_Served,section,medium,none
21,132862,San Luis Potosi,San Luis Potosi,Mexico,Wine-Beer,none,high,none
22,134983,Cuernavaca,Morelos,Mexico,Full_Bar,section,high,none
23,132851,San Luis Potosi,San Luis Potosi,Mexico,No_Alcohol_Served,not permitted,low,none
24,135013,Jiutepec,Morelos,Mexico,No_Alcohol_Served,none,low,none
25,135042,San Luis Potosi,SLP,Mexico,No_Alcohol_Served,none,medium,none
26,132768,cuernavaca,morelos,mexico,No_Alcohol_Served,not permitted,medium,none
27,132561,?,?,?,No_Alcohol_Served,none,low,none
28,135045,San Luis Potosi,SLP,Mexico,Wine-Beer,none,high,none
29,132847,slp,slp,mexico,No_Alcohol_Served,none,low,none
...,...,...,...,...,...,...,...,...
100,134996,Cuernavaca,Morelos,Mexico,Wine-Beer,only at bar,medium,Internet
101,132755,San Luis Potosi,S.L.P.,Mexico,No_Alcohol_Served,none,medium,variety
102,135043,Soledad,SLP,Mexico,No_Alcohol_Served,none,medium,none
103,132654,victoria,tamaulipas,?,No_Alcohol_Served,none,low,none
104,135049,San Luis Potosi,SLP,Mexico,No_Alcohol_Served,none,medium,none
105,135073,San Luis Potosi,SLP,Mexico,Wine-Beer,section,high,none
106,132560,victoria,tamaulipas,mexico,No_Alcohol_Served,permitted,low,none
107,134976,?,?,?,No_Alcohol_Served,none,low,none
108,135075,San Luis Potosi,SLP,Mexico,No_Alcohol_Served,none,medium,none
109,132660,victoria,tamaulipas,?,No_Alcohol_Served,none,low,none
110,132921,?,?,?,Wine-Beer,section,low,none
111,132594,?,?,?,No_Alcohol_Served,not permitted,low,none
112,134986,Cuernavaca,Morelos,Mexico,Wine-Beer,none,high,none
113,135062,San Luis Potosi,SLP,Mexico,No_Alcohol_Served,none,medium,none
114,132766,Cuernavaca,Morelos,Mexico,Wine-Beer,none,medium,none
115,135088,Cuernavaca,Morelos,Mexico,No_Alcohol_Served,not permitted,low,none
116,135058,San Luis Potosi,SLP,Mexico,No_Alcohol_Served,none,medium,none
117,132754,San Luis Potosi,S.L.P.,Mexico,No_Alcohol_Served,none,medium,none
118,132584,?,?,?,No_Alcohol_Served,not permitted,medium,none
119,135032,San Luis Potosi,SLP,Mexico,Wine-Beer,section,medium,none
120,135028,San Luis Potosi,SLP,Mexico,Wine-Beer,none,medium,none
121,135085,San Luis Potosi,SLP,Mexico,No_Alcohol_Served,not permitted,medium,none
122,132663,victoria,tamaulipas,mexico,No_Alcohol_Served,none,low,none
123,132626,victoria,tamaulipas,?,No_Alcohol_Served,none,medium,none
124,132583,Cuernavaca,Morelos,Mexico,No_Alcohol_Served,not permitted,low,none
125,132866,San Luis Potosi,San Luis Potosi,Mexico,No_Alcohol_Served,not permitted,medium,none
126,135072,San Luis Potosi,SLP,Mexico,No_Alcohol_Served,none,medium,none
127,135109,?,?,?,Wine-Beer,not permitted,medium,Internet
128,135019,Jiutepec,Morelos,Mexico,No_Alcohol_Served,none,low,none
129,132877,?,?,?,No_Alcohol_Served,none,low,none

In [34]:
# Menghapus Kolom
Lokasi = Lokasi.drop(['country','alcohol','smoking_area','other_services'], axis=1)
Lokasi

     placeID             city            state   price
0     134999       Cuernavaca          Morelos  medium
1     132825           s.l.p.           s.l.p.     low
2     135106  San Luis Potosi  San Luis Potosi  medium
3     132667        victoria        tamaulipas     low
4     132613         victoria       Tamaulipas  medium
5     135040  San Luis Potosi              SLP    high
6     132732      Cd Victoria       Tamaulipas     low
7     132875                ?                ?    high
8     132609         victoria       Tamaulipas     low
9     135082  San Luis Potosi              SLP  medium
10    135070  San Luis Potosi              SLP  medium
11    135069  San Luis Potosi              SLP     low
12    135065  San Luis Potosi              SLP    high
13    135076  San Luis Potosi              SLP    high
14    135086  San Luis Potosi              SLP  medium
15    132870  San Luis Potosi  San Luis Potosi     low
16    132854  San Luis Potosi  San Luis Potosi  medium
17    132937  san luis potosi  san luis potosi     low
18    132856  San Luis Potosi  San Luis Potosi     low
19    132668         victoria       tamaulipas     low
20    135033  San Luis Potosi              SLP  medium
21    132862  San Luis Potosi  San Luis Potosi    high
22    134983       Cuernavaca          Morelos    high
23    132851  San Luis Potosi  San Luis Potosi     low
24    135013         Jiutepec          Morelos     low
25    135042  San Luis Potosi              SLP  medium
26    132768       cuernavaca          morelos  medium
27    132561                ?                ?     low
28    135045  San Luis Potosi              SLP    high
29    132847              slp              slp     low
..       ...              ...              ...     ...
100   134996       Cuernavaca          Morelos  medium
101   132755  San Luis Potosi           S.L.P.  medium
102   135043          Soledad              SLP  medium
103   132654        victoria        tamaulipas     low
104   135049  San Luis Potosi              SLP  medium
105   135073  San Luis Potosi              SLP    high
106   132560         victoria       tamaulipas     low
107   134976                ?                ?     low
108   135075  San Luis Potosi              SLP  medium
109   132660         victoria       tamaulipas     low
110   132921                ?                ?     low
111   132594                ?                ?     low
112   134986       Cuernavaca          Morelos    high
113   135062  San Luis Potosi              SLP  medium
114   132766       Cuernavaca          Morelos  medium
115   135088       Cuernavaca          Morelos     low
116   135058  San Luis Potosi              SLP  medium
117   132754  San Luis Potosi           S.L.P.  medium
118   132584                ?                ?  medium
119   135032  San Luis Potosi              SLP  medium
120   135028  San Luis Potosi              SLP  medium
121   135085  San Luis Potosi              SLP  medium
122   132663         victoria       tamaulipas     low
123   132626         victoria       tamaulipas  medium
124   132583       Cuernavaca          Morelos     low
125   132866  San Luis Potosi  San Luis Potosi  medium
126   135072  San Luis Potosi              SLP  medium
127   135109                ?                ?  medium
128   135019         Jiutepec          Morelos     low
129   132877                ?                ?     low

[130 rows x 4 columns]

In [35]:
Pembayaran

    userID             Upayment
0    U1001                 cash
1    U1002                 cash
2    U1003                 cash
3    U1004                 cash
4    U1004     bank_debit_cards
5    U1005                 cash
6    U1006                 cash
7    U1007                 cash
8    U1008                 cash
9    U1009                 cash
10   U1010                 cash
11   U1011                 cash
12   U1012                 cash
13   U1012     bank_debit_cards
14   U1013  MasterCard-Eurocard
15   U1013                 cash
16   U1014                 cash
17   U1015                 cash
18   U1016                 cash
19   U1017                 cash
20   U1017                 VISA
21   U1018                 cash
22   U1019                 cash
23   U1020                 cash
24   U1020     bank_debit_cards
25   U1021                 cash
26   U1022                 cash
27   U1023                 cash
28   U1026                 cash
29   U1026     bank_debit_cards
..     ...                  ...
147  U1113                 VISA
148  U1113                 cash
149  U1114                 cash
150  U1115                 cash
151  U1116                 cash
152  U1116     bank_debit_cards
153  U1116                 VISA
154  U1117     bank_debit_cards
155  U1117                 cash
156  U1118                 cash
157  U1119                 cash
158  U1120                 cash
159  U1121                 cash
160  U1121     bank_debit_cards
161  U1123                 cash
162  U1124                 cash
163  U1125                 cash
164  U1126                 cash
165  U1127                 cash
166  U1128                 cash
167  U1129                 cash
168  U1131                 cash
169  U1132                 cash
170  U1133     bank_debit_cards
171  U1133                 cash
172  U1134                 cash
173  U1135                 cash
174  U1136                 cash
175  U1137                 cash
176  U1138                 cash

[177 rows x 2 columns]

In [36]:
Rating

     userID  placeID  rating  food_rating  service_rating
0     U1077   135085       2            2               2
1     U1077   135038       2            2               1
2     U1077   132825       2            2               2
3     U1077   135060       1            2               2
4     U1068   135104       1            1               2
5     U1068   132740       0            0               0
6     U1068   132663       1            1               1
7     U1068   132732       0            0               0
8     U1068   132630       1            1               1
9     U1067   132584       2            2               2
10    U1067   132733       1            1               1
11    U1067   132732       1            2               2
12    U1067   132630       1            0               1
13    U1067   135104       0            0               0
14    U1067   132560       1            0               0
15    U1103   132584       1            2               1
16    U1103   132732       0            0               2
17    U1103   132630       1            2               0
18    U1103   132613       2            2               2
19    U1103   132667       1            2               2
20    U1103   135104       1            2               0
21    U1103   132663       1            0               2
22    U1103   132733       2            2               2
23    U1107   132660       2            2               1
24    U1107   132584       2            2               2
25    U1107   132733       2            2               2
26    U1044   135088       2            2               2
27    U1044   132583       1            2               1
28    U1070   132608       2            2               1
29    U1070   132609       1            1               1
...     ...      ...     ...          ...             ...
1131  U1087   132732       2            2               1
1132  U1087   132740       1            2               1
1133  U1087   132560       1            2               1
1134  U1087   132594       1            2               1
1135  U1087   132663       1            2               1
1136  U1065   132626       1            0               1
1137  U1065   132706       2            1               2
1138  U1129   132561       1            2               2
1139  U1065   132665       1            1               1
1140  U1129   132665       0            0               0
1141  U1065   132561       1            1               1
1142  U1039   132626       2            2               1
1143  U1039   132564       1            1               2
1144  U1065   132654       1            1               1
1145  U1039   132665       1            1               2
1146  U1130   132654       0            0               0
1147  U1130   132561       0            0               0
1148  U1130   132626       0            0               0
1149  U1130   132706       1            2               1
1150  U1043   132608       1            1               1
1151  U1043   132609       1            2               1
1152  U1011   132717       2            2               1
1153  U1043   132613       1            1               1
1154  U1011   132564       1            1               1
1155  U1043   132732       1            1               1
1156  U1043   132630       1            1               1
1157  U1011   132715       1            1               0
1158  U1068   132733       1            1               0
1159  U1068   132594       1            1               1
1160  U1068   132660       0            0               0

[1161 rows x 5 columns]

In [37]:
# unsert new colomn
Rating['rating_total'] =(Rating['rating'] + Rating['food_rating'] + Rating['service_rating'])
Rating

     userID  placeID  rating  food_rating  service_rating  rating_total
0     U1077   135085       2            2               2             6
1     U1077   135038       2            2               1             5
2     U1077   132825       2            2               2             6
3     U1077   135060       1            2               2             5
4     U1068   135104       1            1               2             4
5     U1068   132740       0            0               0             0
6     U1068   132663       1            1               1             3
7     U1068   132732       0            0               0             0
8     U1068   132630       1            1               1             3
9     U1067   132584       2            2               2             6
10    U1067   132733       1            1               1             3
11    U1067   132732       1            2               2             5
12    U1067   132630       1            0               1             2
13    U1067   135104       0            0               0             0
14    U1067   132560       1            0               0             1
15    U1103   132584       1            2               1             4
16    U1103   132732       0            0               2             2
17    U1103   132630       1            2               0             3
18    U1103   132613       2            2               2             6
19    U1103   132667       1            2               2             5
20    U1103   135104       1            2               0             3
21    U1103   132663       1            0               2             3
22    U1103   132733       2            2               2             6
23    U1107   132660       2            2               1             5
24    U1107   132584       2            2               2             6
25    U1107   132733       2            2               2             6
26    U1044   135088       2            2               2             6
27    U1044   132583       1            2               1             4
28    U1070   132608       2            2               1             5
29    U1070   132609       1            1               1             3
...     ...      ...     ...          ...             ...           ...
1131  U1087   132732       2            2               1             5
1132  U1087   132740       1            2               1             4
1133  U1087   132560       1            2               1             4
1134  U1087   132594       1            2               1             4
1135  U1087   132663       1            2               1             4
1136  U1065   132626       1            0               1             2
1137  U1065   132706       2            1               2             5
1138  U1129   132561       1            2               2             5
1139  U1065   132665       1            1               1             3
1140  U1129   132665       0            0               0             0
1141  U1065   132561       1            1               1             3
1142  U1039   132626       2            2               1             5
1143  U1039   132564       1            1               2             4
1144  U1065   132654       1            1               1             3
1145  U1039   132665       1            1               2             4
1146  U1130   132654       0            0               0             0
1147  U1130   132561       0            0               0             0
1148  U1130   132626       0            0               0             0
1149  U1130   132706       1            2               1             4
1150  U1043   132608       1            1               1             3
1151  U1043   132609       1            2               1             4
1152  U1011   132717       2            2               1             5
1153  U1043   132613       1            1               1             3
1154  U1011   132564       1            1               1             3
1155  U1043   132732       1            1               1             3
1156  U1043   132630       1            1               1             3
1157  U1011   132715       1            1               0             2
1158  U1068   132733       1            1               0             2
1159  U1068   132594       1            1               1             3
1160  U1068   132660       0            0               0             0

[1161 rows x 6 columns]

In [38]:
# menggabungkan 2 tabel
data = pd.merge(Lokasi,Rating, on="placeID")
data

,placeID,city,state,price,userID,rating,food_rating,service_rating,rating_total
0,134999,Cuernavaca,Morelos,medium,U1093,2,2,2,6
1,134999,Cuernavaca,Morelos,medium,U1066,1,1,1,3
2,134999,Cuernavaca,Morelos,medium,U1040,1,1,1,3
3,134999,Cuernavaca,Morelos,medium,U1110,2,2,2,6
4,134999,Cuernavaca,Morelos,medium,U1121,2,2,2,6
5,132825,s.l.p.,s.l.p.,low,U1077,2,2,2,6
6,132825,s.l.p.,s.l.p.,low,U1055,2,2,2,6
7,132825,s.l.p.,s.l.p.,low,U1053,1,2,0,3
8,132825,s.l.p.,s.l.p.,low,U1081,1,0,1,2
9,132825,s.l.p.,s.l.p.,low,U1001,2,2,1,5
10,132825,s.l.p.,s.l.p.,low,U1056,2,2,2,6
11,132825,s.l.p.,s.l.p.,low,U1134,1,2,1,4
12,132825,s.l.p.,s.l.p.,low,U1116,2,2,2,6
13,132825,s.l.p.,s.l.p.,low,U1024,1,1,0,2
14,132825,s.l.p.,s.l.p.,low,U1132,2,2,2,6
15,132825,s.l.p.,s.l.p.,low,U1036,2,2,2,6
16,132825,s.l.p.,s.l.p.,low,U1071,2,2,2,6
17,132825,s.l.p.,s.l.p.,low,U1049,0,0,0,0
18,132825,s.l.p.,s.l.p.,low,U1104,1,2,1,4
19,132825,s.l.p.,s.l.p.,low,U1045,2,1,1,4
20,132825,s.l.p.,s.l.p.,low,U1009,1,1,0,2
21,132825,s.l.p.,s.l.p.,low,U1135,0,0,0,0
22,132825,s.l.p.,s.l.p.,low,U1062,0,0,0,0
23,132825,s.l.p.,s.l.p.,low,U1109,2,2,2,6
24,132825,s.l.p.,s.l.p.,low,U1085,2,2,2,6
25,132825,s.l.p.,s.l.p.,low,U1098,1,1,1,3
26,132825,s.l.p.,s.l.p.,low,U1003,2,2,1,5
27,132825,s.l.p.,s.l.p.,low,U1091,0,1,1,2
28,132825,s.l.p.,s.l.p.,low,U1029,1,1,0,2
29,132825,s.l.p.,s.l.p.,low,U1137,2,2,1,5
...,...,...,...,...,...,...,...,...,...
1131,132583,Cuernavaca,Morelos,low,U1118,0,0,0,0
1132,132583,Cuernavaca,Morelos,low,U1035,1,0,2,3
1133,132583,Cuernavaca,Morelos,low,U1119,2,2,2,6
1134,132866,San Luis Potosi,San Luis Potosi,medium,U1052,2,2,1,5
1135,132866,San Luis Potosi,San Luis Potosi,medium,U1008,1,1,1,3
1136,132866,San Luis Potosi,San Luis Potosi,medium,U1015,0,1,1,2
1137,132866,San Luis Potosi,San Luis Potosi,medium,U1025,2,1,2,5
1138,132866,San Luis Potosi,San Luis Potosi,medium,U1131,2,2,2,6
1139,135072,San Luis Potosi,SLP,medium,U1083,1,2,2,5
1140,135072,San Luis Potosi,SLP,medium,U1084,2,2,2,6
1141,135072,San Luis Potosi,SLP,medium,U1095,2,2,2,6
1142,135072,San Luis Potosi,SLP,medium,U1013,2,1,1,4
1143,135072,San Luis Potosi,SLP,medium,U1089,1,1,1,3
1144,135072,San Luis Potosi,SLP,medium,U1114,0,0,0,0
1145,135072,San Luis Potosi,SLP,medium,U1096,1,2,1,4
1146,135072,San Luis Potosi,SLP,medium,U1136,1,1,1,3
1147,135109,?,?,medium,U1030,0,0,0,0
1148,135109,?,?,medium,U1020,2,2,1,5
1149,135109,?,?,medium,U1051,1,1,1,3
1150,135109,?,?,medium,U1041,1,2,1,4
1151,135019,Jiutepec,Morelos,low,U1093,2,2,2,6
1152,135019,Jiutepec,Morelos,low,U1030,0,0,0,0
1153,135019,Jiutepec,Morelos,low,U1066,2,1,0,3
1154,135019,Jiutepec,Morelos,low,U1133,1,2,0,3
1155,135019,Jiutepec,Morelos,low,U1040,1,2,1,4
1156,135019,Jiutepec,Morelos,low,U1121,2,2,2,6
1157,132877,?,?,low,U1047,0,0,0,0
1158,132877,?,?,low,U1111,1,1,1,3
1159,132877,?,?,low,U1015,1,1,2,4
1160,132877,?,?,low,U1025,1,1,1,3

In [39]:
# menggabungkan 2 tabel
data1 = pd.merge(Biodata, data, on="userID")
data1

,userID,birth_year,religion,activity,budget,placeID,city,state,price,rating,food_rating,service_rating,rating_total
0,U1001,1989,none,student,medium,132825,s.l.p.,s.l.p.,low,2,2,1,5
1,U1001,1989,none,student,medium,135040,San Luis Potosi,SLP,high,1,1,1,3
2,U1001,1989,none,student,medium,135033,San Luis Potosi,SLP,medium,1,1,1,3
3,U1001,1989,none,student,medium,135045,San Luis Potosi,SLP,high,1,1,1,3
4,U1001,1989,none,student,medium,135025,San Luis Potosi,SLP,medium,2,2,2,6
5,U1001,1989,none,student,medium,135051,San Luis Potosi,SLP,low,1,1,2,4
6,U1001,1989,none,student,medium,132830,?,?,low,1,1,1,3
7,U1001,1989,none,student,medium,135039,San Luis Potosi,SLP,low,1,1,1,3
8,U1001,1989,none,student,medium,135085,San Luis Potosi,SLP,medium,0,1,1,2
9,U1002,1990,Catholic,student,low,132825,s.l.p.,s.l.p.,low,2,2,0,4
10,U1002,1990,Catholic,student,low,135106,San Luis Potosi,San Luis Potosi,medium,1,1,1,3
11,U1002,1990,Catholic,student,low,132862,San Luis Potosi,San Luis Potosi,high,2,2,2,6
12,U1002,1990,Catholic,student,low,135041,San Luis Potosi,SLP,medium,2,1,0,3
13,U1002,1990,Catholic,student,low,132925,?,?,medium,1,1,2,4
14,U1002,1990,Catholic,student,low,135059,San Luis Potosi,SLP,medium,1,2,1,4
15,U1002,1990,Catholic,student,low,135052,San Luis Potosi,SLP,high,1,1,1,3
16,U1002,1990,Catholic,student,low,132921,?,?,low,2,1,1,4
17,U1002,1990,Catholic,student,low,135062,San Luis Potosi,SLP,medium,1,2,1,4
18,U1002,1990,Catholic,student,low,135085,San Luis Potosi,SLP,medium,1,1,1,3
19,U1003,1989,Catholic,student,low,132825,s.l.p.,s.l.p.,low,2,2,1,5
20,U1003,1989,Catholic,student,low,132937,san luis potosi,san luis potosi,low,2,2,1,5
21,U1003,1989,Catholic,student,low,132862,San Luis Potosi,San Luis Potosi,high,1,2,2,5
22,U1003,1989,Catholic,student,low,135079,San Luis Potosi,SLP,high,2,2,2,6
23,U1003,1989,Catholic,student,low,135041,San Luis Potosi,SLP,medium,0,1,1,2
24,U1003,1989,Catholic,student,low,135059,San Luis Potosi,SLP,medium,2,2,2,6
25,U1003,1989,Catholic,student,low,135080,San Luis Potosi,SLP,high,2,1,2,5
26,U1003,1989,Catholic,student,low,135064,San Luis Potosi,SLP,high,0,0,0,0
27,U1003,1989,Catholic,student,low,132723,?,San Luis Potosi,medium,2,2,1,5
28,U1003,1989,Catholic,student,low,132922,?,?,medium,2,2,2,6
29,U1003,1989,Catholic,student,low,132755,San Luis Potosi,S.L.P.,medium,2,2,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1131,U1135,1988,Catholic,student,low,135032,San Luis Potosi,SLP,medium,0,0,0,0
1132,U1135,1988,Catholic,student,low,135028,San Luis Potosi,SLP,medium,0,0,0,0
1133,U1135,1988,Catholic,student,low,135085,San Luis Potosi,SLP,medium,0,0,0,0
1134,U1136,1990,Catholic,student,low,132862,San Luis Potosi,San Luis Potosi,high,2,2,2,6
1135,U1136,1990,Catholic,student,low,135046,San Luis Potosi,SLP,medium,2,2,2,6
1136,U1136,1990,Catholic,student,low,135055,San Luis Potosi,SLP,high,2,2,2,6
1137,U1136,1990,Catholic,student,low,135074,San Luis Potosi,SLP,high,1,1,2,4
1138,U1136,1990,Catholic,student,low,135064,San Luis Potosi,SLP,high,1,1,1,3
1139,U1136,1990,Catholic,student,low,135048,San Luis Potosi,SLP,high,1,2,2,5
1140,U1136,1990,Catholic,student,low,132958,san luis potosi,san luis potos,low,2,2,2,6
1141,U1136,1990,Catholic,student,low,132921,?,?,low,2,2,2,6
1142,U1136,1990,Catholic,student,low,135028,San Luis Potosi,SLP,medium,2,2,2,6
1143,U1136,1990,Catholic,student,low,135072,San Luis Potosi,SLP,medium,1,1,1,3
1144,U1137,1989,Catholic,student,low,132825,s.l.p.,s.l.p.,low,2,2,1,5
1145,U1137,1989,Catholic,student,low,132862,San Luis Potosi,San Luis Potosi,high,2,2,2,6
1146,U1137,1989,Catholic,student,low,135042,San Luis Potosi,SLP,medium,2,2,2,6
1147,U1137,1989,Catholic,student,low,135059,San Luis Potosi,SLP,medium,2,0,2,4
1148,U1137,1989,Catholic,student,low,132723,?,San Luis Potosi,medium,2,2,2,6
1149,U1137,1989,Catholic,student,low,132884,?,?,low,2,2,2,6
1150,U1137,1989,Catholic,student,low,132951,San Luis Potosi,San Luis Potosi,low,2,2,2,6
1151,U1137,1989,Catholic,student,low,132834,san luis potosi,san luis potosi,low,2,2,2,6
1152,U1137,1989,Catholic,student,low,132755,San Luis Potosi,S.L.P.,medium,2,2,2,6
1153,U1137,1989,Catholic,student,low,135049,San Luis Potosi,SLP,medium,2,2,2,6
1154,U1137,1989,Catholic,student,low,135075,San Luis Potosi,SLP,medium,2,2,2,6
1155,U1137,1989,Catholic,student,low,135062,San Luis Potosi,SLP,medium,2,2,2,6
1156,U1137,1989,Catholic,student,low,135058,San Luis Potosi,SLP,medium,0,2,2,4
1157,U1137,1989,Catholic,student,low,135085,San Luis Potosi,SLP,medium,2,1,2,5
1158,U1138,1991,none,student,medium,132925,?,?,medium,1,2,1,4
1159,U1138,1991,none,student,medium,132922,?,?,medium,2,2,2,6
1160,U1138,1991,none,student,medium,132921,?,?,low,2,2,1,5

In [40]:
# menggabungkan tabel
data2 = pd.merge(data1, Pembayaran, on='userID')
data2

,userID,birth_year,religion,activity,budget,placeID,city,state,price,rating,food_rating,service_rating,rating_total,Upayment
0,U1001,1989,none,student,medium,132825,s.l.p.,s.l.p.,low,2,2,1,5,cash
1,U1001,1989,none,student,medium,135040,San Luis Potosi,SLP,high,1,1,1,3,cash
2,U1001,1989,none,student,medium,135033,San Luis Potosi,SLP,medium,1,1,1,3,cash
3,U1001,1989,none,student,medium,135045,San Luis Potosi,SLP,high,1,1,1,3,cash
4,U1001,1989,none,student,medium,135025,San Luis Potosi,SLP,medium,2,2,2,6,cash
5,U1001,1989,none,student,medium,135051,San Luis Potosi,SLP,low,1,1,2,4,cash
6,U1001,1989,none,student,medium,132830,?,?,low,1,1,1,3,cash
7,U1001,1989,none,student,medium,135039,San Luis Potosi,SLP,low,1,1,1,3,cash
8,U1001,1989,none,student,medium,135085,San Luis Potosi,SLP,medium,0,1,1,2,cash
9,U1002,1990,Catholic,student,low,132825,s.l.p.,s.l.p.,low,2,2,0,4,cash
10,U1002,1990,Catholic,student,low,135106,San Luis Potosi,San Luis Potosi,medium,1,1,1,3,cash
11,U1002,1990,Catholic,student,low,132862,San Luis Potosi,San Luis Potosi,high,2,2,2,6,cash
12,U1002,1990,Catholic,student,low,135041,San Luis Potosi,SLP,medium,2,1,0,3,cash
13,U1002,1990,Catholic,student,low,132925,?,?,medium,1,1,2,4,cash
14,U1002,1990,Catholic,student,low,135059,San Luis Potosi,SLP,medium,1,2,1,4,cash
15,U1002,1990,Catholic,student,low,135052,San Luis Potosi,SLP,high,1,1,1,3,cash
16,U1002,1990,Catholic,student,low,132921,?,?,low,2,1,1,4,cash
17,U1002,1990,Catholic,student,low,135062,San Luis Potosi,SLP,medium,1,2,1,4,cash
18,U1002,1990,Catholic,student,low,135085,San Luis Potosi,SLP,medium,1,1,1,3,cash
19,U1003,1989,Catholic,student,low,132825,s.l.p.,s.l.p.,low,2,2,1,5,cash
20,U1003,1989,Catholic,student,low,132937,san luis potosi,san luis potosi,low,2,2,1,5,cash
21,U1003,1989,Catholic,student,low,132862,San Luis Potosi,San Luis Potosi,high,1,2,2,5,cash
22,U1003,1989,Catholic,student,low,135079,San Luis Potosi,SLP,high,2,2,2,6,cash
23,U1003,1989,Catholic,student,low,135041,San Luis Potosi,SLP,medium,0,1,1,2,cash
24,U1003,1989,Catholic,student,low,135059,San Luis Potosi,SLP,medium,2,2,2,6,cash
25,U1003,1989,Catholic,student,low,135080,San Luis Potosi,SLP,high,2,1,2,5,cash
26,U1003,1989,Catholic,student,low,135064,San Luis Potosi,SLP,high,0,0,0,0,cash
27,U1003,1989,Catholic,student,low,132723,?,San Luis Potosi,medium,2,2,1,5,cash
28,U1003,1989,Catholic,student,low,132922,?,?,medium,2,2,2,6,cash
29,U1003,1989,Catholic,student,low,132755,San Luis Potosi,S.L.P.,medium,2,2,1,5,cash
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1398,U1135,1988,Catholic,student,low,135032,San Luis Potosi,SLP,medium,0,0,0,0,cash
1399,U1135,1988,Catholic,student,low,135028,San Luis Potosi,SLP,medium,0,0,0,0,cash
1400,U1135,1988,Catholic,student,low,135085,San Luis Potosi,SLP,medium,0,0,0,0,cash
1401,U1136,1990,Catholic,student,low,132862,San Luis Potosi,San Luis Potosi,high,2,2,2,6,cash
1402,U1136,1990,Catholic,student,low,135046,San Luis Potosi,SLP,medium,2,2,2,6,cash
1403,U1136,1990,Catholic,student,low,135055,San Luis Potosi,SLP,high,2,2,2,6,cash
1404,U1136,1990,Catholic,student,low,135074,San Luis Potosi,SLP,high,1,1,2,4,cash
1405,U1136,1990,Catholic,student,low,135064,San Luis Potosi,SLP,high,1,1,1,3,cash
1406,U1136,1990,Catholic,student,low,135048,San Luis Potosi,SLP,high,1,2,2,5,cash
1407,U1136,1990,Catholic,student,low,132958,san luis potosi,san luis potos,low,2,2,2,6,cash
1408,U1136,1990,Catholic,student,low,132921,?,?,low,2,2,2,6,cash
1409,U1136,1990,Catholic,student,low,135028,San Luis Potosi,SLP,medium,2,2,2,6,cash
1410,U1136,1990,Catholic,student,low,135072,San Luis Potosi,SLP,medium,1,1,1,3,cash
1411,U1137,1989,Catholic,student,low,132825,s.l.p.,s.l.p.,low,2,2,1,5,cash
1412,U1137,1989,Catholic,student,low,132862,San Luis Potosi,San Luis Potosi,high,2,2,2,6,cash
1413,U1137,1989,Catholic,student,low,135042,San Luis Potosi,SLP,medium,2,2,2,6,cash
1414,U1137,1989,Catholic,student,low,135059,San Luis Potosi,SLP,medium,2,0,2,4,cash
1415,U1137,1989,Catholic,student,low,132723,?,San Luis Potosi,medium,2,2,2,6,cash
1416,U1137,1989,Catholic,student,low,132884,?,?,low,2,2,2,6,cash
1417,U1137,1989,Catholic,student,low,132951,San Luis Potosi,San Luis Potosi,low,2,2,2,6,cash
1418,U1137,1989,Catholic,student,low,132834,san luis potosi,san luis potosi,low,2,2,2,6,cash
1419,U1137,1989,Catholic,student,low,132755,San Luis Potosi,S.L.P.,medium,2,2,2,6,cash
1420,U1137,1989,Catholic,student,low,135049,San Luis Potosi,SLP,medium,2,2,2,6,cash
1421,U1137,1989,Catholic,student,low,135075,San Luis Potosi,SLP,medium,2,2,2,6,cash
1422,U1137,1989,Catholic,student,low,135062,San Luis Potosi,SLP,medium,2,2,2,6,cash
1423,U1137,1989,Catholic,student,low,135058,San Luis Potosi,SLP,medium,0,2,2,4,cash
1424,U1137,1989,Catholic,student,low,135085,San Luis Potosi,SLP,medium,2,1,2,5,cash
1425,U1138,1991,none,student,medium,132925,?,?,medium,1,2,1,4,cash
1426,U1138,1991,none,student,medium,132922,?,?,medium,2,2,2,6,cash
1427,U1138,1991,none,student,medium,132921,?,?,low,2,2,1,5,cash

In [42]:
# mengurutkan kolom
data2 = data2[['userID','birth_year','religion','activity','budget','placeID','city','state','Upayment','price','rating','food_rating','service_rating','rating_total']]
data2

,userID,birth_year,religion,activity,budget,placeID,city,state,Upayment,price,rating,food_rating,service_rating,rating_total
0,U1001,1989,none,student,medium,132825,s.l.p.,s.l.p.,cash,low,2,2,1,5
1,U1001,1989,none,student,medium,135040,San Luis Potosi,SLP,cash,high,1,1,1,3
2,U1001,1989,none,student,medium,135033,San Luis Potosi,SLP,cash,medium,1,1,1,3
3,U1001,1989,none,student,medium,135045,San Luis Potosi,SLP,cash,high,1,1,1,3
4,U1001,1989,none,student,medium,135025,San Luis Potosi,SLP,cash,medium,2,2,2,6
5,U1001,1989,none,student,medium,135051,San Luis Potosi,SLP,cash,low,1,1,2,4
6,U1001,1989,none,student,medium,132830,?,?,cash,low,1,1,1,3
7,U1001,1989,none,student,medium,135039,San Luis Potosi,SLP,cash,low,1,1,1,3
8,U1001,1989,none,student,medium,135085,San Luis Potosi,SLP,cash,medium,0,1,1,2
9,U1002,1990,Catholic,student,low,132825,s.l.p.,s.l.p.,cash,low,2,2,0,4
10,U1002,1990,Catholic,student,low,135106,San Luis Potosi,San Luis Potosi,cash,medium,1,1,1,3
11,U1002,1990,Catholic,student,low,132862,San Luis Potosi,San Luis Potosi,cash,high,2,2,2,6
12,U1002,1990,Catholic,student,low,135041,San Luis Potosi,SLP,cash,medium,2,1,0,3
13,U1002,1990,Catholic,student,low,132925,?,?,cash,medium,1,1,2,4
14,U1002,1990,Catholic,student,low,135059,San Luis Potosi,SLP,cash,medium,1,2,1,4
15,U1002,1990,Catholic,student,low,135052,San Luis Potosi,SLP,cash,high,1,1,1,3
16,U1002,1990,Catholic,student,low,132921,?,?,cash,low,2,1,1,4
17,U1002,1990,Catholic,student,low,135062,San Luis Potosi,SLP,cash,medium,1,2,1,4
18,U1002,1990,Catholic,student,low,135085,San Luis Potosi,SLP,cash,medium,1,1,1,3
19,U1003,1989,Catholic,student,low,132825,s.l.p.,s.l.p.,cash,low,2,2,1,5
20,U1003,1989,Catholic,student,low,132937,san luis potosi,san luis potosi,cash,low,2,2,1,5
21,U1003,1989,Catholic,student,low,132862,San Luis Potosi,San Luis Potosi,cash,high,1,2,2,5
22,U1003,1989,Catholic,student,low,135079,San Luis Potosi,SLP,cash,high,2,2,2,6
23,U1003,1989,Catholic,student,low,135041,San Luis Potosi,SLP,cash,medium,0,1,1,2
24,U1003,1989,Catholic,student,low,135059,San Luis Potosi,SLP,cash,medium,2,2,2,6
25,U1003,1989,Catholic,student,low,135080,San Luis Potosi,SLP,cash,high,2,1,2,5
26,U1003,1989,Catholic,student,low,135064,San Luis Potosi,SLP,cash,high,0,0,0,0
27,U1003,1989,Catholic,student,low,132723,?,San Luis Potosi,cash,medium,2,2,1,5
28,U1003,1989,Catholic,student,low,132922,?,?,cash,medium,2,2,2,6
29,U1003,1989,Catholic,student,low,132755,San Luis Potosi,S.L.P.,cash,medium,2,2,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1398,U1135,1988,Catholic,student,low,135032,San Luis Potosi,SLP,cash,medium,0,0,0,0
1399,U1135,1988,Catholic,student,low,135028,San Luis Potosi,SLP,cash,medium,0,0,0,0
1400,U1135,1988,Catholic,student,low,135085,San Luis Potosi,SLP,cash,medium,0,0,0,0
1401,U1136,1990,Catholic,student,low,132862,San Luis Potosi,San Luis Potosi,cash,high,2,2,2,6
1402,U1136,1990,Catholic,student,low,135046,San Luis Potosi,SLP,cash,medium,2,2,2,6
1403,U1136,1990,Catholic,student,low,135055,San Luis Potosi,SLP,cash,high,2,2,2,6
1404,U1136,1990,Catholic,student,low,135074,San Luis Potosi,SLP,cash,high,1,1,2,4
1405,U1136,1990,Catholic,student,low,135064,San Luis Potosi,SLP,cash,high,1,1,1,3
1406,U1136,1990,Catholic,student,low,135048,San Luis Potosi,SLP,cash,high,1,2,2,5
1407,U1136,1990,Catholic,student,low,132958,san luis potosi,san luis potos,cash,low,2,2,2,6
1408,U1136,1990,Catholic,student,low,132921,?,?,cash,low,2,2,2,6
1409,U1136,1990,Catholic,student,low,135028,San Luis Potosi,SLP,cash,medium,2,2,2,6
1410,U1136,1990,Catholic,student,low,135072,San Luis Potosi,SLP,cash,medium,1,1,1,3
1411,U1137,1989,Catholic,student,low,132825,s.l.p.,s.l.p.,cash,low,2,2,1,5
1412,U1137,1989,Catholic,student,low,132862,San Luis Potosi,San Luis Potosi,cash,high,2,2,2,6
1413,U1137,1989,Catholic,student,low,135042,San Luis Potosi,SLP,cash,medium,2,2,2,6
1414,U1137,1989,Catholic,student,low,135059,San Luis Potosi,SLP,cash,medium,2,0,2,4
1415,U1137,1989,Catholic,student,low,132723,?,San Luis Potosi,cash,medium,2,2,2,6
1416,U1137,1989,Catholic,student,low,132884,?,?,cash,low,2,2,2,6
1417,U1137,1989,Catholic,student,low,132951,San Luis Potosi,San Luis Potosi,cash,low,2,2,2,6
1418,U1137,1989,Catholic,student,low,132834,san luis potosi,san luis potosi,cash,low,2,2,2,6
1419,U1137,1989,Catholic,student,low,132755,San Luis Potosi,S.L.P.,cash,medium,2,2,2,6
1420,U1137,1989,Catholic,student,low,135049,San Luis Potosi,SLP,cash,medium,2,2,2,6
1421,U1137,1989,Catholic,student,low,135075,San Luis Potosi,SLP,cash,medium,2,2,2,6
1422,U1137,1989,Catholic,student,low,135062,San Luis Potosi,SLP,cash,medium,2,2,2,6
1423,U1137,1989,Catholic,student,low,135058,San Luis Potosi,SLP,cash,medium,0,2,2,4
1424,U1137,1989,Catholic,student,low,135085,San Luis Potosi,SLP,cash,medium,2,1,2,5
1425,U1138,1991,none,student,medium,132925,?,?,cash,medium,1,2,1,4
1426,U1138,1991,none,student,medium,132922,?,?,cash,medium,2,2,2,6
1427,U1138,1991,none,student,medium,132921,?,?,cash,low,2,2,1,5

In [46]:
# menghapus baris
data2 = data.drop([6,13,16,27,28])
data2

,placeID,city,state,price,userID,rating,food_rating,service_rating,rating_total
0,134999,Cuernavaca,Morelos,medium,U1093,2,2,2,6
1,134999,Cuernavaca,Morelos,medium,U1066,1,1,1,3
2,134999,Cuernavaca,Morelos,medium,U1040,1,1,1,3
3,134999,Cuernavaca,Morelos,medium,U1110,2,2,2,6
4,134999,Cuernavaca,Morelos,medium,U1121,2,2,2,6
5,132825,s.l.p.,s.l.p.,low,U1077,2,2,2,6
7,132825,s.l.p.,s.l.p.,low,U1053,1,2,0,3
8,132825,s.l.p.,s.l.p.,low,U1081,1,0,1,2
9,132825,s.l.p.,s.l.p.,low,U1001,2,2,1,5
10,132825,s.l.p.,s.l.p.,low,U1056,2,2,2,6
11,132825,s.l.p.,s.l.p.,low,U1134,1,2,1,4
12,132825,s.l.p.,s.l.p.,low,U1116,2,2,2,6
14,132825,s.l.p.,s.l.p.,low,U1132,2,2,2,6
15,132825,s.l.p.,s.l.p.,low,U1036,2,2,2,6
17,132825,s.l.p.,s.l.p.,low,U1049,0,0,0,0
18,132825,s.l.p.,s.l.p.,low,U1104,1,2,1,4
19,132825,s.l.p.,s.l.p.,low,U1045,2,1,1,4
20,132825,s.l.p.,s.l.p.,low,U1009,1,1,0,2
21,132825,s.l.p.,s.l.p.,low,U1135,0,0,0,0
22,132825,s.l.p.,s.l.p.,low,U1062,0,0,0,0
23,132825,s.l.p.,s.l.p.,low,U1109,2,2,2,6
24,132825,s.l.p.,s.l.p.,low,U1085,2,2,2,6
25,132825,s.l.p.,s.l.p.,low,U1098,1,1,1,3
26,132825,s.l.p.,s.l.p.,low,U1003,2,2,1,5
29,132825,s.l.p.,s.l.p.,low,U1137,2,2,1,5
30,132825,s.l.p.,s.l.p.,low,U1114,0,0,0,0
31,132825,s.l.p.,s.l.p.,low,U1061,1,2,1,4
32,132825,s.l.p.,s.l.p.,low,U1057,1,1,0,2
33,132825,s.l.p.,s.l.p.,low,U1025,0,0,0,0
34,132825,s.l.p.,s.l.p.,low,U1059,2,1,1,4
...,...,...,...,...,...,...,...,...,...
1131,132583,Cuernavaca,Morelos,low,U1118,0,0,0,0
1132,132583,Cuernavaca,Morelos,low,U1035,1,0,2,3
1133,132583,Cuernavaca,Morelos,low,U1119,2,2,2,6
1134,132866,San Luis Potosi,San Luis Potosi,medium,U1052,2,2,1,5
1135,132866,San Luis Potosi,San Luis Potosi,medium,U1008,1,1,1,3
1136,132866,San Luis Potosi,San Luis Potosi,medium,U1015,0,1,1,2
1137,132866,San Luis Potosi,San Luis Potosi,medium,U1025,2,1,2,5
1138,132866,San Luis Potosi,San Luis Potosi,medium,U1131,2,2,2,6
1139,135072,San Luis Potosi,SLP,medium,U1083,1,2,2,5
1140,135072,San Luis Potosi,SLP,medium,U1084,2,2,2,6
1141,135072,San Luis Potosi,SLP,medium,U1095,2,2,2,6
1142,135072,San Luis Potosi,SLP,medium,U1013,2,1,1,4
1143,135072,San Luis Potosi,SLP,medium,U1089,1,1,1,3
1144,135072,San Luis Potosi,SLP,medium,U1114,0,0,0,0
1145,135072,San Luis Potosi,SLP,medium,U1096,1,2,1,4
1146,135072,San Luis Potosi,SLP,medium,U1136,1,1,1,3
1147,135109,?,?,medium,U1030,0,0,0,0
1148,135109,?,?,medium,U1020,2,2,1,5
1149,135109,?,?,medium,U1051,1,1,1,3
1150,135109,?,?,medium,U1041,1,2,1,4
1151,135019,Jiutepec,Morelos,low,U1093,2,2,2,6
1152,135019,Jiutepec,Morelos,low,U1030,0,0,0,0
1153,135019,Jiutepec,Morelos,low,U1066,2,1,0,3
1154,135019,Jiutepec,Morelos,low,U1133,1,2,0,3
1155,135019,Jiutepec,Morelos,low,U1040,1,2,1,4
1156,135019,Jiutepec,Morelos,low,U1121,2,2,2,6
1157,132877,?,?,low,U1047,0,0,0,0
1158,132877,?,?,low,U1111,1,1,1,3
1159,132877,?,?,low,U1015,1,1,2,4
1160,132877,?,?,low,U1025,1,1,1,3

In [50]:
hasil = pd.merge(data1, Pembayaran, how='inner', on='userID')
hasil

,userID,birth_year,religion,activity,budget,placeID,city,state,price,rating,food_rating,service_rating,rating_total,Upayment
0,U1001,1989,none,student,medium,132825,s.l.p.,s.l.p.,low,2,2,1,5,cash
1,U1001,1989,none,student,medium,135040,San Luis Potosi,SLP,high,1,1,1,3,cash
2,U1001,1989,none,student,medium,135033,San Luis Potosi,SLP,medium,1,1,1,3,cash
3,U1001,1989,none,student,medium,135045,San Luis Potosi,SLP,high,1,1,1,3,cash
4,U1001,1989,none,student,medium,135025,San Luis Potosi,SLP,medium,2,2,2,6,cash
5,U1001,1989,none,student,medium,135051,San Luis Potosi,SLP,low,1,1,2,4,cash
6,U1001,1989,none,student,medium,132830,?,?,low,1,1,1,3,cash
7,U1001,1989,none,student,medium,135039,San Luis Potosi,SLP,low,1,1,1,3,cash
8,U1001,1989,none,student,medium,135085,San Luis Potosi,SLP,medium,0,1,1,2,cash
9,U1002,1990,Catholic,student,low,132825,s.l.p.,s.l.p.,low,2,2,0,4,cash
10,U1002,1990,Catholic,student,low,135106,San Luis Potosi,San Luis Potosi,medium,1,1,1,3,cash
11,U1002,1990,Catholic,student,low,132862,San Luis Potosi,San Luis Potosi,high,2,2,2,6,cash
12,U1002,1990,Catholic,student,low,135041,San Luis Potosi,SLP,medium,2,1,0,3,cash
13,U1002,1990,Catholic,student,low,132925,?,?,medium,1,1,2,4,cash
14,U1002,1990,Catholic,student,low,135059,San Luis Potosi,SLP,medium,1,2,1,4,cash
15,U1002,1990,Catholic,student,low,135052,San Luis Potosi,SLP,high,1,1,1,3,cash
16,U1002,1990,Catholic,student,low,132921,?,?,low,2,1,1,4,cash
17,U1002,1990,Catholic,student,low,135062,San Luis Potosi,SLP,medium,1,2,1,4,cash
18,U1002,1990,Catholic,student,low,135085,San Luis Potosi,SLP,medium,1,1,1,3,cash
19,U1003,1989,Catholic,student,low,132825,s.l.p.,s.l.p.,low,2,2,1,5,cash
20,U1003,1989,Catholic,student,low,132937,san luis potosi,san luis potosi,low,2,2,1,5,cash
21,U1003,1989,Catholic,student,low,132862,San Luis Potosi,San Luis Potosi,high,1,2,2,5,cash
22,U1003,1989,Catholic,student,low,135079,San Luis Potosi,SLP,high,2,2,2,6,cash
23,U1003,1989,Catholic,student,low,135041,San Luis Potosi,SLP,medium,0,1,1,2,cash
24,U1003,1989,Catholic,student,low,135059,San Luis Potosi,SLP,medium,2,2,2,6,cash
25,U1003,1989,Catholic,student,low,135080,San Luis Potosi,SLP,high,2,1,2,5,cash
26,U1003,1989,Catholic,student,low,135064,San Luis Potosi,SLP,high,0,0,0,0,cash
27,U1003,1989,Catholic,student,low,132723,?,San Luis Potosi,medium,2,2,1,5,cash
28,U1003,1989,Catholic,student,low,132922,?,?,medium,2,2,2,6,cash
29,U1003,1989,Catholic,student,low,132755,San Luis Potosi,S.L.P.,medium,2,2,1,5,cash
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1398,U1135,1988,Catholic,student,low,135032,San Luis Potosi,SLP,medium,0,0,0,0,cash
1399,U1135,1988,Catholic,student,low,135028,San Luis Potosi,SLP,medium,0,0,0,0,cash
1400,U1135,1988,Catholic,student,low,135085,San Luis Potosi,SLP,medium,0,0,0,0,cash
1401,U1136,1990,Catholic,student,low,132862,San Luis Potosi,San Luis Potosi,high,2,2,2,6,cash
1402,U1136,1990,Catholic,student,low,135046,San Luis Potosi,SLP,medium,2,2,2,6,cash
1403,U1136,1990,Catholic,student,low,135055,San Luis Potosi,SLP,high,2,2,2,6,cash
1404,U1136,1990,Catholic,student,low,135074,San Luis Potosi,SLP,high,1,1,2,4,cash
1405,U1136,1990,Catholic,student,low,135064,San Luis Potosi,SLP,high,1,1,1,3,cash
1406,U1136,1990,Catholic,student,low,135048,San Luis Potosi,SLP,high,1,2,2,5,cash
1407,U1136,1990,Catholic,student,low,132958,san luis potosi,san luis potos,low,2,2,2,6,cash
1408,U1136,1990,Catholic,student,low,132921,?,?,low,2,2,2,6,cash
1409,U1136,1990,Catholic,student,low,135028,San Luis Potosi,SLP,medium,2,2,2,6,cash
1410,U1136,1990,Catholic,student,low,135072,San Luis Potosi,SLP,medium,1,1,1,3,cash
1411,U1137,1989,Catholic,student,low,132825,s.l.p.,s.l.p.,low,2,2,1,5,cash
1412,U1137,1989,Catholic,student,low,132862,San Luis Potosi,San Luis Potosi,high,2,2,2,6,cash
1413,U1137,1989,Catholic,student,low,135042,San Luis Potosi,SLP,medium,2,2,2,6,cash
1414,U1137,1989,Catholic,student,low,135059,San Luis Potosi,SLP,medium,2,0,2,4,cash
1415,U1137,1989,Catholic,student,low,132723,?,San Luis Potosi,medium,2,2,2,6,cash
1416,U1137,1989,Catholic,student,low,132884,?,?,low,2,2,2,6,cash
1417,U1137,1989,Catholic,student,low,132951,San Luis Potosi,San Luis Potosi,low,2,2,2,6,cash
1418,U1137,1989,Catholic,student,low,132834,san luis potosi,san luis potosi,low,2,2,2,6,cash
1419,U1137,1989,Catholic,student,low,132755,San Luis Potosi,S.L.P.,medium,2,2,2,6,cash
1420,U1137,1989,Catholic,student,low,135049,San Luis Potosi,SLP,medium,2,2,2,6,cash
1421,U1137,1989,Catholic,student,low,135075,San Luis Potosi,SLP,medium,2,2,2,6,cash
1422,U1137,1989,Catholic,student,low,135062,San Luis Potosi,SLP,medium,2,2,2,6,cash
1423,U1137,1989,Catholic,student,low,135058,San Luis Potosi,SLP,medium,0,2,2,4,cash
1424,U1137,1989,Catholic,student,low,135085,San Luis Potosi,SLP,medium,2,1,2,5,cash
1425,U1138,1991,none,student,medium,132925,?,?,medium,1,2,1,4,cash
1426,U1138,1991,none,student,medium,132922,?,?,medium,2,2,2,6,cash
1427,U1138,1991,none,student,medium,132921,?,?,low,2,2,1,5,cash

### Concatenating

In [55]:
R1 = pd.read_csv (r'e:\Documents\rating_1.csv', delimiter=';')  
R2 = pd.read_csv (r'e:\Documents\rating_2.csv', delimiter=';') 
R3 = pd.read_csv (r'e:\Documents\rating_3.csv', delimiter=';')

In [56]:
R1

   userID  placeID  rating  food_rating  service_rating
0   U1077   135085       2            2               2
1   U1077   135038       2            2               1
2   U1077   132825       2            2               2
3   U1077   135060       1            2               2
4   U1068   135104       1            1               2
5   U1068   132740       0            0               0
6   U1068   132663       1            1               1
7   U1068   132732       0            0               0
8   U1068   132630       1            1               1
9   U1067   132584       2            2               2
10  U1067   132733       1            1               1
11  U1067   132732       1            2               2
12  U1067   132630       1            0               1
13  U1067   135104       0            0               0
14  U1067   132560       1            0               0
15  U1103   132584       1            2               1
16  U1103   132732       0            0               2
17  U1103   132630       1            2               0
18  U1103   132613       2            2               2

In [57]:
R2

   userID  placeID  rating  food_rating  service_rating
0   U1103   132667       1            2               2
1   U1103   135104       1            2               0
2   U1103   132663       1            0               2
3   U1103   132733       2            2               2
4   U1107   132660       2            2               1
5   U1107   132584       2            2               2
6   U1107   132733       2            2               2
7   U1044   135088       2            2               2
8   U1044   132583       1            2               1
9   U1070   132608       2            2               1
10  U1070   132609       1            1               1
11  U1070   132613       1            1               0
12  U1031   132663       0            0               0
13  U1031   132665       0            0               0
14  U1031   132668       0            0               0
15  U1082   132630       1            1               1
16  U1023   132715       0            0               0
17  U1023   132717       0            0               0
18  U1082   132613       0            0               0
19  U1082   132594       0            0               0

In [58]:
R3

   userID  placeID  rating  food_rating  service_rating
0   U1082   132608       0            0               0
1   U1082   132609       0            0               0
2   U1082   132663       0            0               0
3   U1082   132560       0            0               0
4   U1060   132564       2            2               2
5   U1060   132717       2            2               2
6   U1060   132733       2            1               2
7   U1060   132740       1            2               1
8   U1015   135071       0            0               0
9   U1123   132733       1            2               1
10  U1123   132608       1            2               1

In [59]:
frames = [R1, R2, R3]
hasil = pd.concat(frames)
hasil

   userID  placeID  rating  food_rating  service_rating
0   U1077   135085       2            2               2
1   U1077   135038       2            2               1
2   U1077   132825       2            2               2
3   U1077   135060       1            2               2
4   U1068   135104       1            1               2
5   U1068   132740       0            0               0
6   U1068   132663       1            1               1
7   U1068   132732       0            0               0
8   U1068   132630       1            1               1
9   U1067   132584       2            2               2
10  U1067   132733       1            1               1
11  U1067   132732       1            2               2
12  U1067   132630       1            0               1
13  U1067   135104       0            0               0
14  U1067   132560       1            0               0
15  U1103   132584       1            2               1
16  U1103   132732       0            0               2
17  U1103   132630       1            2               0
18  U1103   132613       2            2               2
0   U1103   132667       1            2               2
1   U1103   135104       1            2               0
2   U1103   132663       1            0               2
3   U1103   132733       2            2               2
4   U1107   132660       2            2               1
5   U1107   132584       2            2               2
6   U1107   132733       2            2               2
7   U1044   135088       2            2               2
8   U1044   132583       1            2               1
9   U1070   132608       2            2               1
10  U1070   132609       1            1               1
11  U1070   132613       1            1               0
12  U1031   132663       0            0               0
13  U1031   132665       0            0               0
14  U1031   132668       0            0               0
15  U1082   132630       1            1               1
16  U1023   132715       0            0               0
17  U1023   132717       0            0               0
18  U1082   132613       0            0               0
19  U1082   132594       0            0               0
0   U1082   132608       0            0               0
1   U1082   132609       0            0               0
2   U1082   132663       0            0               0
3   U1082   132560       0            0               0
4   U1060   132564       2            2               2
5   U1060   132717       2            2               2
6   U1060   132733       2            1               2
7   U1060   132740       1            2               1
8   U1015   135071       0            0               0
9   U1123   132733       1            2               1
10  U1123   132608       1            2               1

In [60]:
hasil = pd.concat(frames, keys=['X', 'Y', 'Z'])
hasil

     userID  placeID  rating  food_rating  service_rating
X 0   U1077   135085       2            2               2
  1   U1077   135038       2            2               1
  2   U1077   132825       2            2               2
  3   U1077   135060       1            2               2
  4   U1068   135104       1            1               2
  5   U1068   132740       0            0               0
  6   U1068   132663       1            1               1
  7   U1068   132732       0            0               0
  8   U1068   132630       1            1               1
  9   U1067   132584       2            2               2
  10  U1067   132733       1            1               1
  11  U1067   132732       1            2               2
  12  U1067   132630       1            0               1
  13  U1067   135104       0            0               0
  14  U1067   132560       1            0               0
  15  U1103   132584       1            2               1
  16  U1103   132732       0            0               2
  17  U1103   132630       1            2               0
  18  U1103   132613       2            2               2
Y 0   U1103   132667       1            2               2
  1   U1103   135104       1            2               0
  2   U1103   132663       1            0               2
  3   U1103   132733       2            2               2
  4   U1107   132660       2            2               1
  5   U1107   132584       2            2               2
  6   U1107   132733       2            2               2
  7   U1044   135088       2            2               2
  8   U1044   132583       1            2               1
  9   U1070   132608       2            2               1
  10  U1070   132609       1            1               1
  11  U1070   132613       1            1               0
  12  U1031   132663       0            0               0
  13  U1031   132665       0            0               0
  14  U1031   132668       0            0               0
  15  U1082   132630       1            1               1
  16  U1023   132715       0            0               0
  17  U1023   132717       0            0               0
  18  U1082   132613       0            0               0
  19  U1082   132594       0            0               0
Z 0   U1082   132608       0            0               0
  1   U1082   132609       0            0               0
  2   U1082   132663       0            0               0
  3   U1082   132560       0            0               0
  4   U1060   132564       2            2               2
  5   U1060   132717       2            2               2
  6   U1060   132733       2            1               2
  7   U1060   132740       1            2               1
  8   U1015   135071       0            0               0
  9   U1123   132733       1            2               1
  10  U1123   132608       1            2               1